spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ielts_ai}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Koma2626}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  tomcat:
    max-swallow-size: 50MB

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000

gemini:
  api:
    key: ${GEMINI_API_KEY:}
    base-url: https://generativelanguage.googleapis.com/v1beta
    model: ${GEMINI_MODEL:gemini-flash-latest}
    generation:
      temperature: 0.2
      response-mime-type: application/json

springdoc:
  swagger-ui:
    custom-css-url: "/swagger-custom.css"
    custom-js-url: "/swagger-custom.js"